---
name: FlowInsightES
description: "A searchable datastore for FlowInsight. This is an ElasticSearch stack setup with host affinity for client, master and datanodes. "
version: 0.0.1-rancher1
category: FlowInsight
maintainer: Richard Rothwell <richard.rothwell@aarnet.edu.au>
license: Apache2
projectURL: https://git.cdn.aarnet.edu.au/aarnet_network_analytics/flow_insight_rancher
