.catalog:
  name: "FlowInsight"
  version: "2.4.3-rancher1"
  description: "IPFIX data analytics."
  questions:
    - variable: "router_name"
      label: "Router name"
      description: "Name of the router from which will process the IPFIX stream."
      type: "string"
      default: vic-nbpk-pe1
      required: true
    - variable: "router_scale"
      label: "Scale"
      description: "Number of processing instances to use for this router."
      type: "int"
      default: 1
      required: true
flowinsight-farm:
  metadata:
    farm:
      yml:
        router_name: "${router_name}"
        router_scale: "${router_scale}"
