flowinsight-farm:
  image: registry.aarnet.net.au/insight/farm 
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.scheduler.affinity:host_label: flowinsight_role=pipeline
  ports:
    - "9797:22"  
  volumes:
    - "/home/rgr/init_data:/srv/insight/init_data"
  entrypoint:
    - /usr/local/bin/farm_entrypoint.sh
  command:
    - "/srv/insight/init_data"
    - "+blerp26"
    - "%gickle"
