version: '2'
services:
  elasticsearch-datavolume-clients:
    image: elasticsearch:2.4.3-alpine
    entrypoint:
    - /bin/true
    volumes:
    - /opt/rancher/bin
    - /usr/share/elasticsearch/config
    - /usr/share/elasticsearch/data
    links:
    - elasticsearch-masters:es-masters
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
      elasticsearch.datanode.config.version: '0'
  elasticsearch-datanodes:
    image: rancher/elasticsearch-conf:v0.5.0
    links:
    - elasticsearch-masters:es-masters
    volumes_from:
    - elasticsearch-datavolume-datanode
    labels:
      io.rancher.sidekicks: elasticsearch-base-datanode,elasticsearch-datavolume-datanode
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.scheduler.affinity:host_label: es_node=es_data
  elasticsearch-base-datanode:
    image: elasticsearch:2.4.3-alpine
    entrypoint:
    - /opt/rancher/bin/run.sh
    network_mode: container:elasticsearch-datanodes
    links:
    - elasticsearch-masters:es-masters
    volumes_from:
    - elasticsearch-datavolume-datanode
    labels:
      elasticsearch.datanode.config.version: '0'
      io.rancher.container.hostname_override: container_name
  elasticsearch-datavolume-datanode:
    image: elasticsearch:2.4.3-alpine
    entrypoint:
    - /bin/true
    volumes:
    - /opt/rancher/bin
    - /usr/share/elasticsearch/config
    - /usr/share/elasticsearch/data
    links:
    - elasticsearch-masters:es-masters
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
      elasticsearch.datanode.config.version: '0'
  elasticsearch-datavolume-masters:
    image: elasticsearch:2.4.3-alpine
    entrypoint:
    - /bin/true
    volumes:
    - /opt/rancher/bin
    - /usr/share/elasticsearch/config
    - /usr/share/elasticsearch/data
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
      elasticsearch.datanode.config.version: '0'
  elasticsearch-clients:
    image: rancher/elasticsearch-conf:v0.5.0
    links:
    - elasticsearch-masters:es-masters
    volumes_from:
    - elasticsearch-datavolume-clients
    labels:
      io.rancher.sidekicks: elasticsearch-base-clients,elasticsearch-datavolume-clients
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: es_node=es_client
  kopf:
    image: rancher/kopf:v0.4.0
    environment:
      KOPF_ES_SERVERS: es-clients:9200
      KOPF_SERVER_NAME: es.dev
    links:
    - elasticsearch-clients:es-clients
    ports:
    - 80:80/tcp
    labels:
      io.rancher.container.hostname_override: container_name
  elasticsearch-masters:
    image: rancher/elasticsearch-conf:v0.5.0
    volumes_from:
    - elasticsearch-datavolume-masters
    labels:
      io.rancher.sidekicks: elasticsearch-base-master,elasticsearch-datavolume-masters
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: es_node=es_master
  elasticsearch-base-clients:
    image: elasticsearch:2.4.3-alpine
    entrypoint:
    - /opt/rancher/bin/run.sh
    network_mode: container:elasticsearch-clients
    links:
    - elasticsearch-masters:es-masters
    volumes_from:
    - elasticsearch-datavolume-clients
    labels:
      io.rancher.container.hostname_override: container_name
      elasticsearch.client.config.version: '0'
  elasticsearch-base-master:
    image: elasticsearch:2.4.3-alpine
    entrypoint:
    - /opt/rancher/bin/run.sh
    network_mode: container:elasticsearch-masters
    volumes_from:
    - elasticsearch-datavolume-masters
    labels:
      elasticsearch.master.config.version: '0'
      io.rancher.container.hostname_override: container_name
