.catalog:
  name: "Network Registry"
  version: 1.0.0-rancher1
  description: |
    A registry for assigning IP addresses to Organisations. Based on a MariaDB cluster. 
  questions:
    - variable: "mysql_root_password"
      type: string
      required: true
      label: "MySQL Root Password"
      description: "Password given to the root mysql user"
      default: "#root1234"
    - variable: "mysql_database"
      type: string
      required: true
      label: "MySQL Database Name"
      default: "network_registry"
      description: "MySQL database to create"
    - variable: "mysql_user"
      type: string
      required: true
      description: "MySQL user for the created database"
      label: "MySQL DB User"
      default: "flowinsight"
    - variable: "mysql_password"
      type: string
      required: true
      label: "MySQL DB Password"
      default: "flowinsight1234"
      description: "Password for the MySQL user of the created database"
    - variable: "init_directory"
      type: string
      required: true
      label: "Initialisation directory."
      default: "/srv/network_registry/init_data" 
      description: >
          Path to directory containing an SQL dump files used to populate the database. 
          Ensure this directory exists and the dump files are present before activating. "
mariadb-master:
  scale: 1
  metadata:
    mysqld: |
      innodb_file_per_table = 1
      innodb_autoinc_lock_mode=2
      query_cache_size=0
      query_cache_type=0
      innodb_flush_log_at_trx_commit=0
      binlog_format=ROW
      default-storage-engine=innodb
      progress=1
#mariadb-lb:
#  scale: 1
#  load_balancer_config: {}
#  health_check:
#    port: 42
#    interval: 2000
#    unhealthy_threshold: 3
#    healthy_threshold: 2
#    response_timeout: 2000
