.catalog:
  name: "FlowInsight-Kibana-5"
  version: "4.6.3-rancher1"
  description: "FlowInsight: Explore & Visualize IPFIX Stream Data with Kibana 5"
  questions:
    - variable: "elasticsearch_source"
      description: "Link to elasticsearch service or stack/service"
      label: "Elasticsearch source"
      type: "service"
      required: true
      default: "flow-insight-es/elasticsearch-query-clients"
    - variable: "public_port"
      label: "Public Port"
      description: "Unique public port for Kibana"
      type: "int"
      default: 80
      required: true
    - variable: "elasticsearch_url"
      label: "ElasticSearch URL"
      description: "The location of the ElasticSearch client node. "
      type: "string"
      default: "http://elasticsearch:9200"
      required: false
    - variable: "request_timeout"
      label: "Request timeout/ms"
      description: "The time limit in milliseconds for returning a response sent to ElasticSearch with every query. "
      type: "int"
      default: 1200000
      required: false
    - variable: "proxy_read_timeout"
      label: "Proxy read timeout/s"
      description: "The time limit in seconds for Kibana returning a response to nginx. "
      type: "int"
      default: 120
      required: false
    - variable: "xpack_security_enabled"
      label: "X-Pack Security"
      description: "Enforces authentication and authorisation. "
      type: "boolean"
      default: false
      required: false

nginx-proxy:
  metadata:
    nginx:
      conf:
        servername: "kibana"
        upstream_port: 5601
        proxy_read_timeout: ${proxy_read_timeout}
    kibana5:
      conf:
        elasticsearch.url: "${elasticsearch_url}"
        elasticsearch.requestTimeout: ${request_timeout}
        xpack.security.enabled: "${xpack_security_enabled}"
kibana-vip:
  scale: 1
  start_on_create: true
  lb_config:
    certs: []
    config: |-
      defaults
         timeout connect 5000ms
         timeout client 200000ms
         timeout server 200000ms
    port_rules:
    - protocol: http
      service: nginx-proxy
      source_port: 80
      target_port: 80
  health_check:
    response_timeout: 2000
    healthy_threshold: 2
    port: 42
    unhealthy_threshold: 3
    interval: 2000
