---
name: FlowInsight-Kibana-5
description: >
  FlowInsight: Explore & Visualize IPFIX Stream Data with Kibana 5.
version: 0.0.1-rancher1
category: FlowInsight
maintainer: Richard Rothwell <richard.rothwell@aarnet.edu.au>
license: Apache2
projectURL: https://git.cdn.aarnet.edu.au/aarnet_network_analytics/flow_insight_rancher
