.catalog:
  name: "Elasticsearch"
  version: "2.4.3-rancher1"
  description: "Elasticsearch. You know, for search"
  questions:
    - variable: cluster_name
      description: "Unique name to assign to your Elasticsearch cluster."
      label: "Cluster Name"
      type: "string"
      required: true
      default: "flowinsight"
    - variable: "kopf_port"
      label: "Public Port"
      description: "Unique public port for kopf"
      type: "int"
      default: 81
      required: true
elasticsearch-masters:
  metadata:
    elasticsearch:
      yml:
        cluster.name: "${cluster_name}"
        node.name: "$${HOSTNAME}"
        node.data: "false"
        node.master: "true"
        network.host: "_site_"
        script.engine.groovy.inline.aggs: on
# Short term data nodes on SSD storage
elasticsearch-datanodes-0:
  metadata:
    elasticsearch:
      yml:
        cluster.name: "${cluster_name}"
        node.name: "$${HOSTNAME}"
        node.data: "true"
        node.master: "false"
        http.enabled: "false"
        network.host: "_site_"
        #path.data: "/data0,/data1"
        path.data: "/data0"
        #path.work: "/work"
        #path.plugins: "/plugins"
        processors: 5
        cluster.routing.allocation.same_shard.host: "true"
        script.engine.groovy.inline.aggs: on
        node.box_type: hot
# Short term data nodes on SSD storage
elasticsearch-datanodes-1:
  metadata:
    elasticsearch:
      yml:
        cluster.name: "${cluster_name}"
        node.name: "$${HOSTNAME}"
        node.data: "true"
        node.master: "false"
        http.enabled: "false"
        network.host: "_site_"
        #path.data: "/data0,/data1"
        path.data: "/data0"
        #path.work: "/work"
        #path.plugins: "/plugins"
        processors: 5
        cluster.routing.allocation.same_shard.host: "true"
        script.engine.groovy.inline.aggs: on
        node.box_type: hot
# Long term (lt0) data nodes on HD storage
elasticsearch-datanodes-lt0:
  metadata:
    elasticsearch:
      yml:
        cluster.name: "${cluster_name}"
        node.name: "$${HOSTNAME}.lt0"
        node.data: "true"
        node.master: "false"
        http.enabled: "false"
        network.host: "_site_"
        #path.data: "/data0,/data1,/data2,/data3"
        path.data: "/data0,/data1"
        #path.work: "/work"
        #path.plugins: "/plugins"
        processors: 5
        cluster.routing.allocation.same_shard.host: "true"
        script.engine.groovy.inline.aggs: on
        node.box_type: warm
# Long term (lt1) data nodes on HD storage
elasticsearch-datanodes-lt1:
  metadata:
    elasticsearch:
      yml:
        cluster.name: "${cluster_name}"
        node.name: "$${HOSTNAME}.lt1"
        node.data: "true"
        node.master: "false"
        http.enabled: "false"
        network.host: "_site_"
        #path.data: "/data0,/data1,/data2,/data3"
        path.data: "/data0,/data1"
        #path.work: "/work"
        #path.plugins: "/plugins"
        processors: 5
        cluster.routing.allocation.same_shard.host: "true"
        script.engine.groovy.inline.aggs: on
        node.box_type: warm
elasticsearch-query-clients:
  metadata:
    elasticsearch:
      yml:
        cluster.name: "${cluster_name}"
        node.name: "$${HOSTNAME}"
        node.data: "false"
        node.master: "false"
        network.host: "_site_"
        script.engine.groovy.inline.aggs: on
elasticsearch-index-clients:
  metadata:
    elasticsearch:
      yml:
        cluster.name: "${cluster_name}"
        node.name: "$${HOSTNAME}"
        node.data: "false"
        node.master: "false"
        network.host: "_site_"
        script.engine.groovy.inline.aggs: on
