.catalog:
  name: "FlowInsightK"
  version: "4.6.3-rancher1"
  description: "FlowInsight: Explore & Visualize IPFIX Stream Data with Kibana"
  questions:
    - variable: "elasticsearch_source"
      description: "Link to elasticsearch service or stack/service"
      label: "Elasticsearch source"
      type: "service"
      required: true
      default: "flow-insight-es/elasticsearch-query-clients"
    - variable: "public_port"
      label: "Public Port"
      description: "Unique public port for Kibana"
      type: "int"
      default: 80
      required: true
    - variable: "elasticsearch_url"
      label: "ElasticSearch URL"
      description: "The location of the ElasticSearch client node."
      type: "string"
      default: "http://elasticsearch:9200"
      required: false
    - variable: "request_timeout"
      label: "Request timeout/ms"
      description: "The time limit in milliseconds for returning a response sent to ElasticSearch with every query"
      type: "int"
      default: 60000
      required: false

nginx-proxy:
  metadata:
    nginx:
      conf:
        servername: "kibana"
        upstream_port: 5601

flowinsight-kibana4:
  metadata:
    kibana4:
      yml:
        elasticsearch_url: "${elasticsearch_url}"
        request_timeout: "${request_timeout}"
