.catalog:
  name: "Elasticsearch"
  version: "2.4.3-rancher1"
  description: "Elasticsearch. You know, for search"
  questions:
    - variable: cluster_name
      description: "Unique name to assign to your Elasticsearch cluster."
      label: "Cluster Name"
      type: "string"
      required: true
      default: "flowinsight-es"
    - variable: "kopf_port"
      label: "Public Port"
      description: "Unique public port for kopf"
      type: "int"
      default: 81
      required: true
    - variable: "xpack_security_enabled"
      label: "X-Pack Security"
      description: "Enforces authentication and authorisation. "
      type: "boolean"
      default: false
      required: false
    - variable: "threadpool_search_queue_size"
      label: "Search queue size"
      description: "Defines the maximum number of pending searches. Increase if Kibana produces error messages like: 'Courier fetch N of M shards failed'."
      type: "int"
      default: 1000
      required: false
elasticsearch-masters:
  metadata:
    elasticsearch:
      yml:
        cluster.name: "${cluster_name}"
        node.name: "$${HOSTNAME}"
        node.data: "false"
        node.master: "true"
        node.ingest: "false"
        network.host: "_site_"
        script.engine.groovy.inline.aggs: "true"
        thread_pool.search.queue_size: "${threadpool_search_queue_size}"
        xpack.security.enabled: "${xpack_security_enabled}"
# Short term data nodes on SSD storage
elasticsearch-datanodes-0:
  metadata:
    elasticsearch:
      yml:
        cluster.name: "${cluster_name}"
        node.name: "$${HOSTNAME}"
        node.data: "true"
        node.master: "false"
        node.ingest: "false"
        http.enabled: "false"
        network.host: "_site_"
        #path.data: "/data0,/data1"
        path.data: "/data0"
        #path.work: "/work"
        #path.plugins: "/plugins"
        processors: 10
        cluster.routing.allocation.same_shard.host: "true"
        script.engine.groovy.inline.aggs: "true"
        node.attr.box_type: hot
        thread_pool.search.queue_size: "${threadpool_search_queue_size}"
        xpack.security.enabled: "${xpack_security_enabled}"
# Short term data nodes on SSD storage
elasticsearch-datanodes-1:
  metadata:
    elasticsearch:
      yml:
        cluster.name: "${cluster_name}"
        node.name: "$${HOSTNAME}"
        node.data: "true"
        node.master: "false"
        node.ingest: "false"
        http.enabled: "false"
        network.host: "_site_"
        #path.data: "/data0,/data1"
        path.data: "/data0"
        #path.work: "/work"
        #path.plugins: "/plugins"
        processors: 10
        cluster.routing.allocation.same_shard.host: "true"
        script.engine.groovy.inline.aggs: "true"
        node.attr.box_type: hot
        thread_pool.search.queue_size: "${threadpool_search_queue_size}"
        xpack.security.enabled: "${xpack_security_enabled}"
# Long term (lt0) data nodes on HD storage
elasticsearch-datanodes-lt0:
  metadata:
    elasticsearch:
      yml:
        cluster.name: "${cluster_name}"
        node.name: "$${HOSTNAME}.lt0"
        node.data: "true"
        node.master: "false"
        node.ingest: "false"
        http.enabled: "false"
        network.host: "_site_"
        #path.data: "/data0,/data1,/data2,/data3"
        path.data: "/data0,/data1"
        #path.work: "/work"
        #path.plugins: "/plugins"
        processors: 10
        cluster.routing.allocation.same_shard.host: "true"
        script.engine.groovy.inline.aggs: "true"
        node.attr.box_type: warm
        thread_pool.search.queue_size: "${threadpool_search_queue_size}"
        xpack.security.enabled: "${xpack_security_enabled}"
# Long term (lt1) data nodes on HD storage
elasticsearch-datanodes-lt1:
  metadata:
    elasticsearch:
      yml:
        cluster.name: "${cluster_name}"
        node.name: "$${HOSTNAME}.lt1"
        node.data: "true"
        node.master: "false"
        node.ingest: "false"
        http.enabled: "false"
        network.host: "_site_"
        #path.data: "/data0,/data1,/data2,/data3"
        path.data: "/data0,/data1"
        #path.work: "/work"
        #path.plugins: "/plugins"
        processors: 10
        cluster.routing.allocation.same_shard.host: "true"
        script.engine.groovy.inline.aggs: "true"
        node.attr.box_type: warm
        thread_pool.search.queue_size: "${threadpool_search_queue_size}"
        xpack.security.enabled: "${xpack_security_enabled}"
elasticsearch-query-clients:
  metadata:
    elasticsearch:
      yml:
        cluster.name: "${cluster_name}"
        node.name: "$${HOSTNAME}"
        node.data: "false"
        node.master: "false"
        node.ingest: "false"
        network.host: "_site_"
        script.engine.groovy.inline.aggs: "true"
        thread_pool.search.queue_size: "${threadpool_search_queue_size}"
        xpack.security.enabled: "${xpack_security_enabled}"
elasticsearch-index-clients:
  metadata:
    elasticsearch:
      yml:
        cluster.name: "${cluster_name}"
        node.name: "$${HOSTNAME}"
        node.data: "false"
        node.master: "false"
        node.ingest: "true"
        network.host: "_site_"
        script.engine.groovy.inline.aggs: "true"
        thread_pool.search.queue_size: "${threadpool_search_queue_size}"
        xpack.security.enabled: "${xpack_security_enabled}"
