.catalog:
  name: "FlowInsight Reporter"
  version: "2.4.3-rancher1"
  description: "IPFIX data reporting."
  questions:
#    - variable: "reporting_password"
#      type: string
#      required: true
#      label: "Reporting DB Password"
#      default: "gerfuffle!!"
#      description: "Password for the reporting user of the reporting database. "
flowinsight-reporter:
  metadata:
    farm:
      yml:
        reporting_password: "${reporting_password}"
